{
 "title": "BackBlaze progress",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Uploaded since ${__from:date:DD.MM. hh.mm}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_MB\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: false, columns: [\"_value\"])\r\n  |> cumulativeSum(columns: [\"_value\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "options": {
    "content": "<img height=\"130\" src=\"https://i.imgur.com/VjGMHeD_d.webp?maxwidth=1520&fidelity=grand\"/>"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"selected_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Selected for backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"selected_files\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Selected for backup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"selected_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Remaining Files",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_files\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Remaining Data",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Remaining Files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_files\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Remaining Data to backup",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"backblaze\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"backblaze_ui\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 15, "x": 0, "y": 20 }, "options": { "content": "#\r\n# Individual drives" } },
  {
   "title": "Remaining Files",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"drives\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_files\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Remaining Data to backup",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"drives\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"remaining_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Selected Files",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"drives\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"selected_files\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Selected Data to backup",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"Backblaze\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"drives\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"selected_MB\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}